### ISSUE TITLE
Meson build fail

### ISSUE THREAD

**Issue by Rabidax** [Dudemanguy911/vmn#4]
Hi,

Just tried to install it, but `meson build`  fails. Here's the log

> Build started at 2019-06-02T13:23:07.033906
> Main binary: /usr/bin/python3
> Python system: Linux
> The Meson build system
> Version: 0.45.1
> Source dir: /home/username/repo/vmn
> Build dir: /home/username/repo/vmn/build
> Build type: native build
> 
> meson_options.txt:3:0: ERROR: Unknown type feature.

Thanks in advance for any help with that

**Comment by Rabidax** [comment]
I tried commenting the problematic line out, but then that raises an other error later on and meson build still fails.

**Comment by Dudemanguy** [comment]
Ah, `feature` type requires meson 0.47 and higher. Upgrade your meson version if you can. Thanks for pointing this out. I'll update the README.

If you can't update meson for whatever reason, you can just comment out all the scdoc-related lines in `meson_options.txt` and `meson.build` as a dirty workaround.
